title: PPPig's TreeHole
subtitle: 希望你是我的花
description: learnLess
keywords: XTZhu
author: XTZhu
url: "http://XTZhu.github.io"
language: 'zh-CN'
timezone: 'Asia/Shanghai'

root: /
permalink: ":year/:month/:day/:title/"
permalink_defaults: null
pretty_urls:
  trailing_index: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: null
new_post_name: ":title.md"
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
index_generator:
  path: ""
  per_page: 10
  order_by: "-date"
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: "HH:mm:ss"
use_date_for_updated: false
per_page: 10
pagination_dir: page
include: []
exclude: []
ignore: null
theme: next
deploy:
  type: git
  repository: "git@github.com:XTZhu/XTZhu.github.io.git"
  branch: master
canvas_nest: true
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub: null
  content: null
  content_limit: 140
  content_limit_delim: " "
  order_by: "-date"
  icon: icon.png
passage_end_tag:
  enabled: true
leancloud_visitors:
  enable: ture
  app_id: d8WUyrmuMh0Uyaf96GoRmRvM-gzGzoHsz
  app_key: tQqxvI4Cx72qv3KMUbNniQiC
favicon:
  small: /images/deer.png
  medium: /images/deer.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true
  totalcount: true
  separated_meta: true
scrollpercent: true
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
